### ISSUE TITLE
Create script for experiment design CSV file

### ISSUE THREAD

**Issue by hechth** [RECETOX/RAMClustR#2]
Write a script which takes all the entries as inputs and writes it to a properly formatted csv file, similar to the defineExperiment() function

https://github.com/RECETOX/RAMClustR/blob/master/R/defineExperiment.R

**Comment by xtrojak** [comment]
This functionality will be covered in a [Galaxy wrapper](https://github.com/RECETOX/galaxytools/issues/216), as the function `defineExperiment` actually allows to create and also load `csv` file with experimental design definition.
